---
# Sensitive variables - encrypted with ansible-vault
# To edit: ansible-vault edit group_vars/vault.yml
# To encrypt: ansible-vault encrypt group_vars/vault.yml
# To decrypt: ansible-vault decrypt group_vars/vault.yml

# SSH public key for pi user
vault_ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCv0nTiV3h8G5Gv7e10Ny8BRBu1lKjjVdNWRuMhFTYXJ+fMIGSgraS06lC+arUBVwbtWaTZzbbiJwVaYLbT3lFnNMa6DRB+Th10jimT/mUmvYxUIOeI4pUY1DDyBfSPTeSHrvF70H0axOxNNm2cmiQFXCHT+LHGZtCo0tb9ndtvG8u0et9NfXmzZNvNASJJwDIyIEr3OVdEBqjDFhhkddsJyLUqNHoeNqlWNPQAy+7Tb0U/W+KixLmd8RYkupVhAWBG6wiDRL/WBKC1RrW8AI6g9U1F6r2nzzWy5dOsovZYlcZKdCtCiIqwYzeQvKVIYNuhPpm90zxUkmh3WMHZhWm/OLE0I5W8UgoIe9LWIWJoOFTOUYNzoqS/xyWEraGYsZ3H24XZsKZccVpErzZoCfIJMjvltdt+gUX11wAmuY41sgFgifbh2W9BVuX93xbh7PPlEp3KtLSABry15p2DUSQtr2khWK2vzchr5uHezJs21OmEPhTJUEXdqS/XmKwwek= spencerrung@Spencers-MacBook-Pro.local"

# Default pi user password (optional - can also remove)
vault_pi_password: "raspberry"
